version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  setup-node:
    steps:
      - node/install:
          node-version: latest

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup-node
      - run:
          name: Run tests
          command: npm test

workflows:
  run-ci:
    jobs:
      - test