version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps: 
      - checkout       
      - run: npm test
      - store_test_results: 
          path: target/surefire-reports
      
          
